import type { CSSProperties, HTMLAttributes, ReactNode, Ref } from "react";

type ZmIntrinsic = HTMLAttributes<HTMLElement> & {
  ref?: Ref<HTMLElement>;
  class?: string;
  style?: CSSProperties;
  children?: ReactNode;
  [attr: string]: unknown;
};

declare global {
  namespace JSX {
    interface IntrinsicElements {
      "zm-badge": ZmIntrinsic;
      "zm-agreement": ZmIntrinsic;
      "zm-alphabet-keypad": ZmIntrinsic;
      "zm-asset": ZmIntrinsic;
      "zm-bar-chart": ZmIntrinsic;
      "zm-board-row": ZmIntrinsic;
      "zm-border": ZmIntrinsic;
      "zm-bottom-cta": ZmIntrinsic;
      "zm-bottom-info": ZmIntrinsic;
      "zm-bottom-sheet": ZmIntrinsic;
      "zm-bubble": ZmIntrinsic;
      "zm-button": ZmIntrinsic;
      "zm-card": ZmIntrinsic;
      "zm-checkbox": ZmIntrinsic;
      "zm-dialog": ZmIntrinsic;
      "zm-grid-list": ZmIntrinsic;
      "zm-heading": ZmIntrinsic;
      "zm-highlight": ZmIntrinsic;
      "zm-icon-button": ZmIntrinsic;
      "zm-loader": ZmIntrinsic;
      "zm-menu": ZmIntrinsic;
      "zm-modal": ZmIntrinsic;
      "zm-list-footer": ZmIntrinsic;
      "zm-list-header": ZmIntrinsic;
      "zm-list-row": ZmIntrinsic;
      "zm-number-keypad": ZmIntrinsic;
      "zm-numeric-spinner": ZmIntrinsic;
      "zm-paragraph": ZmIntrinsic;
      "zm-post": ZmIntrinsic;
      "zm-progress-bar": ZmIntrinsic;
      "zm-progress-stepper": ZmIntrinsic;
      "zm-rating": ZmIntrinsic;
      "zm-result": ZmIntrinsic;
      "zm-search-field": ZmIntrinsic;
      "zm-section": ZmIntrinsic;
      "zm-segmented-control": ZmIntrinsic;
      "zm-secure-keypad": ZmIntrinsic;
      "zm-skeleton": ZmIntrinsic;
      "zm-slider": ZmIntrinsic;
      "zm-spinner": ZmIntrinsic;
      "zm-split-text-field": ZmIntrinsic;
      "zm-stepper": ZmIntrinsic;
      "zm-switch": ZmIntrinsic;
      "zm-tab": ZmIntrinsic;
      "zm-table-row": ZmIntrinsic;
      "zm-text": ZmIntrinsic;
      "zm-text-area": ZmIntrinsic;
      "zm-text-button": ZmIntrinsic;
      "zm-text-field": ZmIntrinsic;
      "zm-toast": ZmIntrinsic;
      "zm-tooltip": ZmIntrinsic;
      "zm-top": ZmIntrinsic;
      "zm-splash-screen": ZmIntrinsic;
      "zm-tab-bars": ZmIntrinsic;
      "zm-snackbar": ZmIntrinsic;
      "zm-quantity-toggle": ZmIntrinsic;
      "zm-back-button": ZmIntrinsic;
      "zm-range-slider": ZmIntrinsic;
      "zm-visually-hidden": ZmIntrinsic;
      "zm-accessible-multimedia": ZmIntrinsic;
      "zm-resize": ZmIntrinsic;
      "zm-language-switcher": ZmIntrinsic;
      "zm-file-upload": ZmIntrinsic;
      "zm-text-input": ZmIntrinsic;
      "zm-date-input": ZmIntrinsic;
      "zm-tts": ZmIntrinsic;
      "zm-coach-mark": ZmIntrinsic;
      "zm-contextual-help": ZmIntrinsic;
      "zm-tutorial-panel": ZmIntrinsic;
      "zm-help-panel": ZmIntrinsic;
      "zm-step-indicator": ZmIntrinsic;
      "zm-toggle-switch": ZmIntrinsic;
      "zm-tag": ZmIntrinsic;
      "zm-select": ZmIntrinsic;
      "zm-radio-button": ZmIntrinsic;
      "zm-fab": ZmIntrinsic;
      "zm-link": ZmIntrinsic;
      "zm-favicon": ZmIntrinsic;
      "zm-text-list": ZmIntrinsic;
      "zm-table": ZmIntrinsic;
      "zm-carousel": ZmIntrinsic;
      "zm-image": ZmIntrinsic;
      "zm-accordion": ZmIntrinsic;
      "zm-disclosure": ZmIntrinsic;
      "zm-calendar": ZmIntrinsic;
      "zm-critical-alert": ZmIntrinsic;
      "zm-structured-list": ZmIntrinsic;
      "zm-pagination": ZmIntrinsic;
      "zm-in-page-navigation": ZmIntrinsic;
      "zm-side-navigation": ZmIntrinsic;
      "zm-breadcrumb": ZmIntrinsic;
      "zm-main-menu": ZmIntrinsic;
      "zm-skip-link": ZmIntrinsic;
      "zm-footer": ZmIntrinsic;
      "zm-header": ZmIntrinsic;
      "zm-identifier": ZmIntrinsic;
      "zm-masthead": ZmIntrinsic;
    }
  }
}

export {};
